---
# tasks file for pplznet-netbox-newcluster
- name: create cluster as site in netbox if not exist
  netbox.netbox.netbox_site:
    netbox_url: "{{ pplznet_netbox_url }}"
    netbox_token: "{{ pplznet_netbox_token }}"
    data:
      name: "{{ pplznet_cluster_name }}"
      region: "pplznet"
    state: present
- name: create prefix for cluster
  netbox.netbox.netbox_prefix:
    netbox_url: "{{ pplznet_netbox_url }}"
    netbox_token: "{{ pplznet_netbox_token }}"
    data:
      parent: "{{ pplznet_netbox_rootula }}"
      prefix_length: 32
    state: present
    first_available: yes
  register: prefix_info
